# Required
version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Image to use
build:
  image: testing

# Configuration
python:
  version: 3.9
  install:
    - method: pip
      path: .
      
